### ISSUE TITLE
IRC Nick doesn't handle Brackets

### ISSUE THREAD

**Issue by BlueCrystal** [Fugiman/txoffer#12]
As the description says, here's the exception error:

Failed to load application: invalid syntax (txoffer.yaml, line 1)

weeaboo@tori:~/txoffer$ twistd -y txoffer.py
Unhandled Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 657, in run
    runApp(config)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/scripts/twistd.py", line 23, in runApp
    _SomeApplicationRunner(config).run()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 389, in run
    self.application = self.createOrGetApplication()
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 454, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/application/app.py", line 465, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/application/service.py", line 403, in loadApplication
    application = sob.loadValueFromFile(filename, 'application', passphrase)
  File "/usr/local/lib/python2.7/dist-packages/Twisted-15.2.0-py2.7-linux-x86_64.egg/twisted/persisted/sob.py", line 210, in loadValueFromFile
    exec fileObj in d, d
  File "txoffer.py", line 1273, in <module>
    Master().setServiceParent(application)
  File "txoffer.py", line 826, in __init__
    self.validateConfig(self.config)
  File "txoffer.py", line 1065, in validateConfig
    raise ConfigException("irc nickname must be a string")
**builtin**.ConfigException: irc nickname must be a string

Failed to load application: irc nickname must be a string

weeaboo@tori:~/txoffer$
Using username "root".

**Comment by adongy** [comment]
Could you paste your config ? (config.yaml)
